# FROM java:8-jdk-alpine


FROM adoptopenjdk/openjdk11:alpine-jre

RUN apk add --update ca-certificates && rm -rf /var/cache/apk/* && \
  find /usr/share/ca-certificates/mozilla/ -name "*.crt" -exec keytool -import -trustcacerts \
  -keystore /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/cacerts -storepass changeit -noprompt \
  -file {} -alias {} \; && \
  keytool -list -keystore /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/cacerts --storepass changeit

ENV MAVEN_VERSION 3.5.4
ENV MAVEN_HOME /usr/lib/mvn
ENV PATH $MAVEN_HOME/bin:$PATH

RUN wget http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  tar -zxvf apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  rm apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  mv apache-maven-$MAVEN_VERSION /usr/lib/mvn

#RUN apk update 
#RUN apk add --update maven --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/community/ --allow-untrusted \
#    && rm -rf /var/cache/apk/*

RUN mkdir -p /app/src
WORKDIR /app/src
COPY . /app/src

RUN mv -f src/main/resources/maven.settings/settings.xml /usr/lib/mvn/conf/settings.xml

#RUN mvn clean package  -Dmaven.test.skip=true
RUN mvn clean package
RUN ls target/

RUN cp target/ak-service-0.0.1-SNAPSHOT-jar-with-dependencies.jar  /app/ak-service-0.0.1-SNAPSHOT-jar-with-dependencies.jar

RUN rm -r /app/src

WORKDIR /app
RUN ls 

CMD ["/bin/bash"]
#ENTRYPOINT ["java","-jar","ak-service-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]